# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=15, null=True)),
                ('activity', models.CharField(default=None, max_length=100, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 12, 4, 23, 25, 37, 834354, tzinfo=utc))),
                ('trigger', models.CharField(default=None, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
