# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 23:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20161204_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 4, 23, 55, 32, 765634, tzinfo=utc)),
        ),
    ]
