# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 5, 3, 7, 17, 993605, tzinfo=utc)),
        ),
    ]
