# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 00:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20161204_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 12, 5, 0, 20, 23, 377652, tzinfo=utc), verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2016, 12, 5, 1, 20, 23, 377717, tzinfo=utc), verbose_name='Ending Appointment Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 12, 5, 0, 20, 23, 377683, tzinfo=utc), verbose_name='Starting Appointment Time'),
        ),
    ]
