# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.EmailField(default='', max_length=50)),
                ('to', models.EmailField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2016, 12, 4, 23, 25, 37, 838500, tzinfo=utc), verbose_name='Date')),
                ('time', models.TimeField(default=datetime.datetime(2016, 12, 4, 23, 25, 37, 838604, tzinfo=utc), verbose_name='Time')),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
