# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20161204_2000'),
        ('messaging', '0009_auto_20161204_1940'),
    ]

    operations = [
    ]
