# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20161204_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='hospital',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 12, 5, 1, 0, 57, 110283, tzinfo=utc), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Hospital'),
        ),
    ]
