# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 23:25
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_records/%Y/%m/%d/')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 12, 4, 23, 25, 37, 835553, tzinfo=utc), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('medicalrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medrecord.MedicalRecord')),
                ('medication', models.CharField(default='', max_length=100)),
                ('dosage', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Dosage should be greater than 0 mg/mL', regex='^[1-9][0-9]*$')], verbose_name='Dosage(mg or mL[for liquids])')),
                ('description', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Quantity should be greater than 0 mg/mL', regex='^[1-9][0-9]*$')], verbose_name='Quantity(mg or mL[for liquids])')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Patient')),
            ],
            bases=('medrecord.medicalrecord',),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('medicalrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medrecord.MedicalRecord')),
                ('description', models.CharField(max_length=200, null=True)),
                ('released', models.BooleanField(default=True)),
            ],
            bases=('medrecord.medicalrecord',),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Patient'),
        ),
    ]
