# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 23:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medrecord', '0003_auto_20161204_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 4, 23, 58, 54, 663196, tzinfo=utc), editable=False),
        ),
    ]
