# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 03:07
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medrecord', '0010_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 5, 3, 7, 17, 996106, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Dosage should be greater than 0 doses', regex='^[1-9][0-9]*$')], verbose_name='Dosage(Doses)'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Quantity should be greater than 0 mg/mL and specify mg or mL', regex='^[1-9][0-9]*\\s?(mg|mL)$')], verbose_name='Quantity(mg or mL[for liquids])'),
        ),
    ]
